// coned_scraper/frontend/src/components/PdfViewer.vue
<template>
  <div
    class="ha-pdf-overlay"
    @click.self="$emit('close')"
  >
    <!-- Header -->
    <div class="ha-pdf-header">
      <span class="ha-pdf-title">📄 Latest Bill</span>
      <div class="ha-pdf-controls">
        <button class="ha-pdf-ctrl" title="Zoom out" @click="zoomOut">−</button>
        <span class="ha-pdf-scale">{{ Math.round(scale * 100) }}%</span>
        <button class="ha-pdf-ctrl" title="Zoom in" @click="zoomIn">+</button>
        <button class="ha-pdf-ctrl ha-pdf-fit" title="Fit" @click="fitToWidth">Fit</button>
        <div class="ha-pdf-divider"></div>
        <button class="ha-pdf-ctrl" :disabled="pageNumber <= 1" @click="goToPrevPage">‹</button>
        <span class="ha-pdf-pages">{{ pageNumber }} / {{ numPages }}</span>
        <button class="ha-pdf-ctrl" :disabled="pageNumber >= numPages" @click="goToNextPage">›</button>
      </div>
      <button class="ha-pdf-close" @click="$emit('close')">✕</button>
    </div>

    <!-- PDF Content -->
    <div class="ha-pdf-body">
      <div v-if="loading" class="ha-pdf-loading">
        <div>Loading PDF...</div>
        <img :src="ajaxLoader" alt="Loading" class="ha-pdf-loader-img" />
      </div>
      <div v-else-if="error" class="ha-pdf-error">
        <div class="ha-pdf-error-icon">📄</div>
        <div>{{ error }}</div>
        <button class="ha-pdf-open-btn" @click="openDirect">Open PDF Directly</button>
      </div>
      <VuePdfEmbed
        v-else
        :source="url"
        :page="pageNumber"
        :width="pageWidth"
        @loaded="onLoaded"
        @loading-failed="onLoadError"
      />
    </div>

    <!-- Mobile Footer -->
    <div class="ha-pdf-footer">
      <button
        class="ha-pdf-nav-btn"
        :disabled="pageNumber <= 1"
        :class="{ disabled: pageNumber <= 1 }"
        @click="goToPrevPage"
      >
        ← Previous
      </button>
      <span class="ha-pdf-footer-pages">Page {{ pageNumber }} of {{ numPages }}</span>
      <button
        class="ha-pdf-nav-btn"
        :disabled="pageNumber >= numPages"
        :class="{ disabled: pageNumber >= numPages }"
        @click="goToNextPage"
      >
        Next →
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ajaxLoader } from '../lib/assets'
import VuePdfEmbed from 'vue-pdf-embed'

const props = defineProps<{
  url: string
}>()

defineEmits<{ (e: 'close'): void }>()

const numPages = ref(0)
const pageNumber = ref(1)
const scale = ref(1)
const loading = ref(true)
const error = ref<string | null>(null)
const pageWidth = computed(() => Math.min(800, window.innerWidth - 48) * scale.value)

function onLoaded(pdf: { numPages: number }) {
  numPages.value = pdf.numPages
  loading.value = false
  error.value = null
}

function onLoadError() {
  error.value = 'Failed to load PDF'
  loading.value = false
}

function goToPrevPage() {
  pageNumber.value = Math.max(pageNumber.value - 1, 1)
}
function goToNextPage() {
  pageNumber.value = Math.min(pageNumber.value + 1, numPages.value)
}
function zoomIn() {
  scale.value = Math.min(scale.value + 0.25, 3)
}
function zoomOut() {
  scale.value = Math.max(scale.value - 0.25, 0.5)
}
function fitToWidth() {
  scale.value = 1
}
function openDirect() {
  window.open(props.url, '_blank')
}
</script>

<style scoped>
.ha-pdf-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.95);
  display: flex;
  flex-direction: column;
  z-index: 9999;
}
.ha-pdf-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem 1rem;
  background: #1a1a2e;
  border-bottom: 1px solid #333;
  flex-shrink: 0;
}
.ha-pdf-title { color: white; font-weight: 500; }
.ha-pdf-controls {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}
.ha-pdf-ctrl {
  background: #333;
  border: none;
  color: white;
  padding: 0.3rem 0.6rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
  min-width: 30px;
}
.ha-pdf-ctrl:disabled { opacity: 0.5; cursor: not-allowed; }
.ha-pdf-fit { font-size: 0.7rem; padding: 0.3rem 0.5rem; }
.ha-pdf-scale { color: white; font-size: 0.8rem; min-width: 50px; text-align: center; }
.ha-pdf-pages { color: white; font-size: 0.8rem; min-width: 60px; text-align: center; }
.ha-pdf-divider { width: 1px; height: 20px; background: #444; margin: 0 0.5rem; }
.ha-pdf-close {
  background: none;
  border: none;
  color: white;
  font-size: 1.5rem;
  cursor: pointer;
  padding: 0.25rem 0.5rem;
}
.ha-pdf-body {
  flex: 1;
  overflow: auto;
  display: flex;
  justify-content: center;
  align-items: flex-start;
  padding: 1rem;
  background: #525659;
}
.ha-pdf-loading {
  color: white;
  padding: 2rem;
  text-align: center;
}
.ha-pdf-loader-img { width: 40px; margin-top: 1rem; display: block; margin-left: auto; margin-right: auto; }
.ha-pdf-error {
  color: #ff6b6b;
  padding: 2rem;
  text-align: center;
}
.ha-pdf-error-icon { font-size: 3rem; margin-bottom: 1rem; }
.ha-pdf-open-btn {
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  background: #03a9f4;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
.ha-pdf-footer {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
  padding: 0.75rem;
  background: #1a1a2e;
  border-top: 1px solid #333;
}
.ha-pdf-nav-btn {
  background: #03a9f4;
  border: none;
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.85rem;
  font-weight: 500;
}
.ha-pdf-nav-btn.disabled { opacity: 0.5; cursor: not-allowed; }
.ha-pdf-footer-pages { color: white; font-size: 0.9rem; }
</style>

// coned-scraper/app/components/PdfViewer.tsx
'use client'

import { useState, useCallback } from 'react'
import { Document, Page, pdfjs } from 'react-pdf'

// Set up PDF.js worker
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`

interface PdfViewerProps {
  url: string
  onClose: () => void
}

export default function PdfViewer({ url, onClose }: PdfViewerProps) {
  const [numPages, setNumPages] = useState<number>(0)
  const [pageNumber, setPageNumber] = useState<number>(1)
  const [scale, setScale] = useState<number>(1)
  const [loading, setLoading] = useState<boolean>(true)
  const [error, setError] = useState<string | null>(null)

  const onDocumentLoadSuccess = useCallback(({ numPages }: { numPages: number }) => {
    setNumPages(numPages)
    setLoading(false)
    setError(null)
  }, [])

  const onDocumentLoadError = useCallback((error: Error) => {
    console.error('PDF load error:', error)
    setError('Failed to load PDF')
    setLoading(false)
  }, [])

  const goToPrevPage = () => setPageNumber(prev => Math.max(prev - 1, 1))
  const goToNextPage = () => setPageNumber(prev => Math.min(prev + 1, numPages))
  const zoomIn = () => setScale(prev => Math.min(prev + 0.25, 3))
  const zoomOut = () => setScale(prev => Math.max(prev - 0.25, 0.5))
  const fitToWidth = () => setScale(1)

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.95)',
        display: 'flex',
        flexDirection: 'column',
        zIndex: 9999
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose()
      }}
    >
      {/* Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '0.75rem 1rem',
        backgroundColor: '#1a1a2e',
        borderBottom: '1px solid #333',
        flexShrink: 0
      }}>
        <span style={{ color: 'white', fontWeight: 500 }}>📄 Latest Bill</span>
        
        {/* Controls */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          {/* Zoom controls */}
          <button onClick={zoomOut} style={controlButtonStyle} title="Zoom out">−</button>
          <span style={{ color: 'white', fontSize: '0.8rem', minWidth: '50px', textAlign: 'center' }}>
            {Math.round(scale * 100)}%
          </span>
          <button onClick={zoomIn} style={controlButtonStyle} title="Zoom in">+</button>
          <button onClick={fitToWidth} style={{...controlButtonStyle, fontSize: '0.7rem', padding: '0.3rem 0.5rem'}} title="Fit">Fit</button>
          
          <div style={{ width: '1px', height: '20px', backgroundColor: '#444', margin: '0 0.5rem' }} />
          
          {/* Page navigation */}
          <button onClick={goToPrevPage} disabled={pageNumber <= 1} style={controlButtonStyle}>‹</button>
          <span style={{ color: 'white', fontSize: '0.8rem', minWidth: '60px', textAlign: 'center' }}>
            {pageNumber} / {numPages}
          </span>
          <button onClick={goToNextPage} disabled={pageNumber >= numPages} style={controlButtonStyle}>›</button>
        </div>

        <button
          onClick={onClose}
          style={{
            background: 'none',
            border: 'none',
            color: 'white',
            fontSize: '1.5rem',
            cursor: 'pointer',
            padding: '0.25rem 0.5rem'
          }}
        >
          ✕
        </button>
      </div>

      {/* PDF Content */}
      <div style={{
        flex: 1,
        overflow: 'auto',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'flex-start',
        padding: '1rem',
        backgroundColor: '#525659'
      }}>
        {loading && (
          <div style={{ color: 'white', padding: '2rem', textAlign: 'center' }}>
            <div style={{ marginBottom: '1rem' }}>Loading PDF...</div>
            <img src="/images/ajax-loader.gif" alt="Loading" style={{ width: '40px' }} />
          </div>
        )}
        
        {error && (
          <div style={{ color: '#ff6b6b', padding: '2rem', textAlign: 'center' }}>
            <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>📄</div>
            <div>{error}</div>
            <button
              onClick={() => window.open(url, '_blank')}
              style={{
                marginTop: '1rem',
                padding: '0.5rem 1rem',
                backgroundColor: '#03a9f4',
                color: 'white',
                border: 'none',
                borderRadius: '4px',
                cursor: 'pointer'
              }}
            >
              Open PDF Directly
            </button>
          </div>
        )}

        <Document
          file={url}
          onLoadSuccess={onDocumentLoadSuccess}
          onLoadError={onDocumentLoadError}
          loading=""
        >
          <Page
            pageNumber={pageNumber}
            scale={scale}
            renderTextLayer={false}
            renderAnnotationLayer={false}
            loading=""
          />
        </Document>
      </div>

      {/* Mobile-friendly page navigation footer */}
      <div style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '1rem',
        padding: '0.75rem',
        backgroundColor: '#1a1a2e',
        borderTop: '1px solid #333'
      }}>
        <button
          onClick={goToPrevPage}
          disabled={pageNumber <= 1}
          style={{
            ...mobileNavButtonStyle,
            opacity: pageNumber <= 1 ? 0.5 : 1
          }}
        >
          ← Previous
        </button>
        <span style={{ color: 'white', fontSize: '0.9rem' }}>
          Page {pageNumber} of {numPages}
        </span>
        <button
          onClick={goToNextPage}
          disabled={pageNumber >= numPages}
          style={{
            ...mobileNavButtonStyle,
            opacity: pageNumber >= numPages ? 0.5 : 1
          }}
        >
          Next →
        </button>
      </div>
    </div>
  )
}

const controlButtonStyle: React.CSSProperties = {
  background: '#333',
  border: 'none',
  color: 'white',
  padding: '0.3rem 0.6rem',
  borderRadius: '4px',
  cursor: 'pointer',
  fontSize: '1rem',
  minWidth: '30px'
}

const mobileNavButtonStyle: React.CSSProperties = {
  background: '#03a9f4',
  border: 'none',
  color: 'white',
  padding: '0.5rem 1rem',
  borderRadius: '4px',
  cursor: 'pointer',
  fontSize: '0.85rem',
  fontWeight: 500
}
